services:
  outsie:
    image: ${DOCKER_USERNAME}/outstagram:${LATEST_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8671:8671"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - OUTSTAGRAM_SECRET_KEY=${OUTSTAGRAM_SECRET_KEY:-jwtkeynotset}
      - OUTSTAGRAM_PASSWORD=${OUTSTAGRAM_PASSWORD:-passnotset}
      - OUTSTAGRAM_DBHOST=${OUTSTAGRAM_DBHOST:-dbhostnotset}
      - OUTSTAGRAM_DBNAME=${OUTSTAGRAM_DBNAME:-dbnamenotset}
      - OUTSTAGRAM_USERNAME=${OUTSTAGRAM_USERNAME:-unamenotset}
      - OUTSTAGRAM_ALLOWED_ORIGIN_1=${OUTSTAGRAM_ALLOWED_ORIGIN_1:-allowedorigin1envnotset}
      - OUTSTAGRAM_ALLOWED_ORIGIN_2=${OUTSTAGRAM_ALLOWED_ORIGIN_2:-allowedorigin2envnotset}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-awsaccesskeyenvnotset}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-awssecretaccesskeyenvnotset}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-awsdefaultregionenvnotset}
      - S3_BUCKET=${S3_BUCKET:-s3bucketenvnotset}
      - S3_ENDPOINT=${S3_ENDPOINT:-s3endpointenvnotset}
      - S3_REGION=${S3_REGION:-s3regionenvnotset}
    env_file:
      - .env.production
