services:
  outsie:
    image: ${DOCKER_USERNAME}/outstagram:${LATEST_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8671:8671"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - OUTSTAGRAM_SECRET_KEY=${OUTSTAGRAM_SECRET_KEY:-passnotset}
      - OUTSTAGRAM_PASSWORD=${OUTSTAGRAM_MYSQL_PASSWORD:-passnotset}
      - OUTSTAGRAM_DBHOST=mysql
      - OUTSTAGRAM_DBNAME=${OUTSTAGRAM_DBNAME:-passnotset}
      - OUTSTAGRAM_USERNAME=${OUTSTAGRAM_USERNAME:-passnotset}
    env_file:
      - .env.production
