services:
  outsie:
    image: ${DOCKER_USERNAME}/outstagram:${LATEST_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8671:8671"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - OUTSTAGRAM_SECRET_KEY=${OUTSTAGRAM_SECRET_KEY:-jwtkeynotset}
      - OUTSTAGRAM_PASSWORD=${OUTSTAGRAM_PASSWORD:-passnotset}
      - OUTSTAGRAM_DBHOST=${OUTSTAGRAM_DBHOST:-dbhostnotset}
      - OUTSTAGRAM_DBNAME=${OUTSTAGRAM_DBNAME:-dbnamenotset}
      - OUTSTAGRAM_USERNAME=${OUTSTAGRAM_USERNAME:-unamenotset}
      - OUTSTAGRAM_ALLOWED_ORIGIN_1=${OUTSTAGRAM_ALLOWED_ORIGIN_1:-allowedorigin1envnotset}
      - OUTSTAGRAM_ALLOWED_ORIGIN_2=${OUTSTAGRAM_ALLOWED_ORIGIN_2:-allowedorigin2envnotset}
    env_file:
      - .env.production
