#!/usr/bin/bash

#curl -X POST \
#  -H "Content-Type: application/json" \
#  -d '{
#    "user_id": "32",
#    "fullname": "iron",
#    "username": "cyto",
#    "bio": "out of order",
#    "email": "silverstone965@gmail.com",
#    "password": "12345678",
#    "date_of_birth": "2003-08-14"
#  }' \
#  http://127.0.0.1:8000/register


#curl -X POST http://localhost:8000/login \
#  -H "Content-Type: application/x-www-form-urlencoded" \
#  -d "username=cyto&password=12345678"


curl -X POST "http://localhost:8000/posts" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN5dG8iLCJleHAiOjE3MzU0MDIwNDh9.YheCKn6lsuaAv3peORZ6eWCAvUsNQBiPOst4rHT9ThE" \
-H "Content-Type: application/json" \
-d '{
    "post_id": "dummy",
    "media_urls": ["https://avatar.iran.liara.run/public/girl"],
    "highlighted_by_author": true,
    "caption": "This is the second test post.",
    "post_category": "entertainment",
    "datetime_posted": "2024-01-02",
    "author": "cyto"
}'

