"""add exam_title to exams table

Revision ID: 0b590aee64c6
Revises: 624cab3d3a70
Create Date: 2025-08-28 12:11:49.363880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b590aee64c6'
down_revision: Union[str, None] = '624cab3d3a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('exam_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='default_title'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'exam_title')
    # ### end Alembic commands ###
