"""add_difficulty_to_question

Revision ID: 15778b7a6961
Revises: 61fd3f652607
Create Date: 2026-08-13 21:06:39.685875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '15778b7a6961'
down_revision: Union[str, None] = '61fd3f652607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type in the database
    difficulty_enum = sa.Enum('easy', 'medium', 'hard', name='difficulty')
    difficulty_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('question', sa.Column('difficulty', difficulty_enum, nullable=False, server_default='medium'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'difficulty')
    # Drop the Enum type
    sa.Enum(name='difficulty').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
