"""add datetime_uploaded to exam table

Revision ID: 4029fa3735ec
Revises: 0b590aee64c6
Create Date: 2025-08-28 16:00:44.398288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4029fa3735ec'
down_revision: Union[str, None] = '0b590aee64c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('datetime_uploaded', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'datetime_uploaded')
    # ### end Alembic commands ###
