"""Describe the changes

Revision ID: 5561bcf7a605
Revises: 
Create Date: 2025-03-09 20:36:45.775105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5561bcf7a605'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('followrequest_requester_user_id_fkey', 'followrequest', type_='foreignkey')
    op.drop_constraint('followrequest_requested_user_id_fkey', 'followrequest', type_='foreignkey')
    op.create_foreign_key(None, 'followrequest', 'user', ['requested_user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'followrequest', 'user', ['requester_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('friendship_user2_id_fkey', 'friendship', type_='foreignkey')
    op.drop_constraint('friendship_user1_id_fkey', 'friendship', type_='foreignkey')
    op.create_foreign_key(None, 'friendship', 'user', ['user2_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friendship', 'user', ['user1_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('mediaurl_post_id_fkey', 'mediaurl', type_='foreignkey')
    op.create_foreign_key(None, 'mediaurl', 'post', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.drop_constraint('post_author_user_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['author_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('postcomment_author_user_id_fkey', 'postcomment', type_='foreignkey')
    op.drop_constraint('postcomment_post_id_fkey', 'postcomment', type_='foreignkey')
    op.create_foreign_key(None, 'postcomment', 'user', ['author_user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'postcomment', 'post', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.drop_constraint('postcommentlike_liker_user_id_fkey', 'postcommentlike', type_='foreignkey')
    op.drop_constraint('postcommentlike_comment_id_fkey', 'postcommentlike', type_='foreignkey')
    op.create_foreign_key(None, 'postcommentlike', 'user', ['liker_user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'postcommentlike', 'postcomment', ['comment_id'], ['comment_id'], ondelete='CASCADE')
    op.drop_constraint('postlike_liker_user_id_fkey', 'postlike', type_='foreignkey')
    op.drop_constraint('postlike_post_id_fkey', 'postlike', type_='foreignkey')
    op.create_foreign_key(None, 'postlike', 'post', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'postlike', 'user', ['liker_user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'postlike', type_='foreignkey')
    op.drop_constraint(None, 'postlike', type_='foreignkey')
    op.create_foreign_key('postlike_post_id_fkey', 'postlike', 'post', ['post_id'], ['post_id'])
    op.create_foreign_key('postlike_liker_user_id_fkey', 'postlike', 'user', ['liker_user_id'], ['user_id'])
    op.drop_constraint(None, 'postcommentlike', type_='foreignkey')
    op.drop_constraint(None, 'postcommentlike', type_='foreignkey')
    op.create_foreign_key('postcommentlike_comment_id_fkey', 'postcommentlike', 'postcomment', ['comment_id'], ['comment_id'])
    op.create_foreign_key('postcommentlike_liker_user_id_fkey', 'postcommentlike', 'user', ['liker_user_id'], ['user_id'])
    op.drop_constraint(None, 'postcomment', type_='foreignkey')
    op.drop_constraint(None, 'postcomment', type_='foreignkey')
    op.create_foreign_key('postcomment_post_id_fkey', 'postcomment', 'post', ['post_id'], ['post_id'])
    op.create_foreign_key('postcomment_author_user_id_fkey', 'postcomment', 'user', ['author_user_id'], ['user_id'])
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_author_user_id_fkey', 'post', 'user', ['author_user_id'], ['user_id'])
    op.drop_constraint(None, 'mediaurl', type_='foreignkey')
    op.create_foreign_key('mediaurl_post_id_fkey', 'mediaurl', 'post', ['post_id'], ['post_id'])
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.create_foreign_key('friendship_user1_id_fkey', 'friendship', 'user', ['user1_id'], ['user_id'])
    op.create_foreign_key('friendship_user2_id_fkey', 'friendship', 'user', ['user2_id'], ['user_id'])
    op.drop_constraint(None, 'followrequest', type_='foreignkey')
    op.drop_constraint(None, 'followrequest', type_='foreignkey')
    op.create_foreign_key('followrequest_requested_user_id_fkey', 'followrequest', 'user', ['requested_user_id'], ['user_id'])
    op.create_foreign_key('followrequest_requester_user_id_fkey', 'followrequest', 'user', ['requester_user_id'], ['user_id'])
    # ### end Alembic commands ###
