"""add media_type to mediaurl

Revision ID: 5a718dbd0c6f
Revises: 4029fa3735ec
Create Date: 2025-11-08 18:40:35.391188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a718dbd0c6f'
down_revision: Union[str, None] = '4029fa3735ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaurl', sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='image'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediaurl', 'media_type')
    # ### end Alembic commands ###
