"""Add question bank and exam sections

Revision ID: 61fd3f652607
Revises: 5a718dbd0c6f
Create Date: 2026-03-26 01:56:42.024147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61fd3f652607'
down_revision: Union[str, None] = '5a718dbd0c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sectionquestionlink_section_id_fkey', 'sectionquestionlink', type_='foreignkey')
    op.drop_constraint('examsection_pkey', 'examsection', type_='primary')
    op.add_column('examsection', sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_primary_key('examsection_pkey', 'examsection', ['id'])
    op.drop_column('examsection', 'section_id')
    op.create_foreign_key(None, 'sectionquestionlink', 'examsection', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sectionquestionlink', type_='foreignkey')
    op.create_foreign_key('sectionquestionlink_section_id_fkey', 'sectionquestionlink', 'examsection', ['section_id'], ['section_id'])
    op.add_column('examsection', sa.Column('section_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('examsection', 'id')
    # ### end Alembic commands ###
