"""add exams table

Revision ID: 624cab3d3a70
Revises: 5561bcf7a605
Create Date: 2025-08-28 12:01:59.831061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '624cab3d3a70'
down_revision: Union[str, None] = '5561bcf7a605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
