"""add_topic_grouping

Revision ID: 694d9080706e
Revises: 15778b7a6961
Create Date: 2026-08-13 23:16:22.456051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '694d9080706e'
down_revision: Union[str, None] = '15778b7a6961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topicgroup',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topicgrouplink',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['topicgroup.group_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topicgrouplink')
    op.drop_table('topicgroup')
    # ### end Alembic commands ###
